### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by DigiAngel** [dunbarcyber/cyphondock#12]
Did a brand new setup from scratch, running production.  Currently getting a 502 Bad Gateway when accessing 5601.  In no order here's the errors I see scrolling through:
~~~
cadvisor_1       | E0519 21:24:19.808628       1 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: <nil>, rootInodeErr: cmd [find /rootfs/var/lib/docker/aufs/diff/d8c72ce1b08a2e236852bf2a97977880daaf384472ca77e1c3e28b2deac69bde -xdev -printf .] failed. stderr: find: unrecognized: -printf
logspout_1       | 2017/05/19 21:24:19 syslog: write udp 172.18.0.10:37126->172.18.0.8:5000: write: connection refused
cadvisor_1       | BusyBox v1.24.2 (2017-01-18 14:13:46 GMT) multi-call binary.
cadvisor_1       |
cadvisor_1       | Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]
cadvisor_1       |
cadvisor_1       | Search for files and perform actions on them.
cadvisor_1       | First failed action stops processing of current file.
cadvisor_1       | Defaults: PATH is current directory, action is '-print'
cadvisor_1       |
cadvisor_1       |      -L,-follow      Follow symlinks
cadvisor_1       |      -H              ...on command line only
cadvisor_1       |      -xdev           Don't descend directories on other filesystems
cadvisor_1       |      -maxdepth N     Descend at most N levels. -maxdepth 0 applies
cadvisor_1       |                      actions to command line arguments only
cadvisor_1       |      -mindepth N     Don't act on first N levels
cadvisor_1       |      -depth          Act on directory *after* traversing it
cadvisor_1       |
cadvisor_1       | Actions:
cadvisor_1       |      ( ACTIONS )     Group actions for -o / -a
cadvisor_1       |      ! ACT           Invert ACT's success/failure
cadvisor_1       |      ACT1 [-a] ACT2  If ACT1 fails, stop, else do ACT2
cadvisor_1       |      ACT1 -o ACT2    If ACT1 succeeds, stop, else do ACT2
cadvisor_1       |                      Note: -a has higher priority than -o
cadvisor_1       |      -name PATTERN   Match file name (w/o directory name) to PATTERN
cadvisor_1       |      -iname PATTERN  Case insensitive -name
cadvisor_1       |      -path PATTERN   Match path to PATTERN
cadvisor_1       |      -ipath PATTERN  Case insensitive -path
cadvisor_1       |      -regex PATTERN  Match path to regex PATTERN
cadvisor_1       |      -type X         File type is X (one of: f,d,l,b,c,...)
cadvisor_1       |      -perm MASK      At least one mask bit (+MASK), all bits (-MASK),
cadvisor_1       |                      or exactly MASK bits are set in file's mode
cadvisor_1       |      -mtime DAYS     mtime is greater than (+N), less than (-N),
cadvisor_1       |                      or exactly N days in the past
cadvisor_1       |      -mmin MINS      mtime is greater than (+N), less than (-N),
cadvisor_1       |                      or exactly N minutes in the past
cadvisor_1       |      -newer FILE     mtime is more recent than FILE's
cadvisor_1       |      -inum N         File has inode number N
cadvisor_1       |      -user NAME/ID   File is owned by given user
cadvisor_1       |      -group NAME/ID  File is owned by given group
cadvisor_1       |      -size N[bck]    File size is N (c:bytes,k:kbytes,b:512 bytes(def.))
cadvisor_1       |                      +/-N: file size is bigger/smaller than N
cadvisor_1       |      -links N        Number of links is greater than (+N), less than (-N),
cadvisor_1       |                      or exactly N
cadvisor_1       |      -prune          If current file is directory, don't descend into it
cadvisor_1       | If none of the following actions is specified, -print is assumed
cadvisor_1       |      -print          Print file name
cadvisor_1       |      -print0         Print file name, NUL terminated
cadvisor_1       |      -exec CMD ARG ; Run CMD with all instances of {} replaced by
cadvisor_1       |                      file name. Fails if CMD exits with nonzero
cadvisor_1       |      -exec CMD ARG + Run CMD with {} replaced by list of file names
cadvisor_1       |      -delete         Delete current file/directory. Turns on -depth option
cadvisor_1       | ; err: exit status 1, extraDiskErr: <nil>
~~~

and:
~~~
lasticsearch_1  | [2017-05-19T21:27:20,004][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2017-05-19T21:27:20,032][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to created node environment
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to created node environment
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      ... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_121]
elasticsearch_1  |      at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_121]
elasticsearch_1  |      at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_121]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:262) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      ... 6 more
~~~

and:
~~~
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2017-05-19T21:23:15,248][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
logstash_1       | [2017-05-19T21:23:15,581][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"4fcc9ff3-c19f-44fd-8e8d-270f905794f3", :path=>"/usr/share/logstash/data/uuid"}
logstash_1       | [2017-05-19T21:23:16,450][ERROR][logstash.agent           ] Cannot load an invalid configuration {:reason=>"Expected one of #, input, filter, output at line 33, column 1 (byte 807) after "}
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2017-05-19T21:24:22,513][ERROR][logstash.agent           ] Cannot load an invalid configuration {:reason=>"Expected one of #, input, filter, output at line 33, column 1 (byte 807) after "}
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2017-05-19T21:25:01,736][ERROR][logstash.agent           ] Cannot load an invalid configuration {:reason=>"Expected one of #, input, filter, output at line 33, column 1 (byte 807) after "}
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2017-05-19T21:25:37,988][ERROR][logstash.agent           ] Cannot load an invalid configuration {:reason=>"Expected one of #, input, filter, output at line 33, column 1 (byte 807) after "}
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2017-05-19T21:26:29,468][ERROR][logstash.agent           ] Cannot load an invalid configuration {:reason=>"Expected one of #, input, filter, output at line 33, column 1 (byte 807) after "}
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2017-05-19T21:27:08,230][ERROR][logstash.agent           ] Cannot load an invalid configuration {:reason=>"Expected one of #, input, filter, output at line 33, column 1 (byte 807) after "}
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2017-05-19T21:27:46,544][ERROR][logstash.agent           ] Cannot load an invalid configuration {:reason=>"Expected one of #, input, filter, output at line 33, column 1 (byte 807) after "}
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2017-05-19T21:28:17,375][ERROR][logstash.agent           ] Cannot load an invalid configuration {:reason=>"Expected one of #, input, filter, output at line 33, column 1 (byte 807) after "}
~~~

Not sure what else to test at this point.  Thank you.

**Comment by lhadjchikh** [comment]
Sorry about that! Somehow an extra character snuck into one of the Logstash filter configs. I just pushed the fix in commit [f9f2976](https://github.com/dunbarcyber/cyphondock/commit/f9f2976bb6cd09fae42c8429b24cfcb7f6c55eab#diff-08ff4202e9502e89e7ea62845109a812), but you can just delete the first character of your ``config/logstash/pipeline/2-filter1-bro.conf`` file (the "1" is a typo).

As for Elasticsearch, I've had problems with the ``AccessDeniedException`` Java error lately as well, and unfortunately I'm not sure yet what's causing it. The only "fix" I've found so far is to not specify the directory for the volume, and instead change lines 22-24 in ``docker-compose.override.yml`` to:

```
  elasticsearch:
    volumes:
      - /usr/share/elasticsearch/data
```
 
This should fix both the Elasticsearch error and the Kibana 502 Bad Gateway, but it's a less than ideal solution, so I'll go back to troubleshooting it on Monday.

Eventually I'll have some integration tests to catch these problems with the container orchestration, but I apologize for the trouble in the meantime! Thanks for your patience and the continued bug reports. :-)

**Comment by lhadjchikh** [comment]
I've been doing some testing around the Kibana 502 Bad Gateway error, and I think if you get Elasticsearch going it should go away. The Kibana container may take a while to fully start, though, so give it a few minutes. If it's definitely not working even with Elasticsearch running, let me know!

**Comment by DigiAngel** [comment]
Awesome thanks...I'll make the changes and report here on Monday.

**Comment by lhadjchikh** [comment]
It looks like the user that owns the elasticsearch data volume needs to have uid "1000". If `id -u $(whoami)` is `1000`, you can just fix the ownership of that directory:
```
sudo chown -R $(whoami):$(whoami) /opt/cyphon/data/elasticsearch
```
Let me know if that fixes it for you!

**Comment by patsToms** [comment]
I just tested your solution. Owner change helps to fix "Failed to created node environment" error in Elasticsearch.

**Comment by lhadjchikh** [comment]
That's good to hear! I will update the docs accordingly.

**Comment by lhadjchikh** [comment]
Docs are updated in commit [03c3446](https://github.com/dunbarcyber/cyphon/commit/03c3446) and should be live [here](http://cyphon.readthedocs.io/en/latest/getting-started/install-cyphon.html). Thanks for testing, @patsToms!

**Comment by DigiAngel** [comment]
And FYI:
~~~
filebeat_1       | filebeat2017/05/24 19:40:19.422843 beat.go:339: CRIT Exiting: error loading config file: config file ("filebeat.yml") can only be writable by the owner but the permissions are "-rw-rw-r--" (to fix the permissions use: 'chmod go-w /usr/share/filebeat/filebeat.yml')
~~~
changing this to rw by owner only fixed this up.

**Comment by lhadjchikh** [comment]
Thanks! I only added the Filebeat service recently so folks could use it for locally testing their Logstash configs. I will make that change!

**Comment by DigiAngel** [comment]
Thanks...the last error I still see is the caadvisor one...other then that I'm running clean :)

**Comment by lhadjchikh** [comment]
I don't think I've ever run into the cAdvisor error before, although from Googling it, it seems you're not alone. It might be something specific to your platform, so you can check out the [documentation](https://github.com/google/cadvisor/blob/master/docs/running.md) to see if anything pertains. cAdvisor is kind of an extra, though, so you can just comment it out of the configs if you'd like. I want to look into [Dockbeat](https://www.elastic.co/blog/dockbeat-a-new-addition-to-the-beats-community) as a possible substitute when I find the time!

**Comment by DigiAngel** [comment]
Hi again....which config file controls cadvisor usage?  The only one I can find is the nginx.conf file.  Thank you.

**Comment by lhadjchikh** [comment]
I haven't added any special configurations for it. It appears in [docker-compose.yml](https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.yml), [docker-compose.dev.yml](https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.dev.yml), [docker-compose.travis.yml](https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.travis.yml) and [nginx.conf](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/nginx/nginx.conf), though. You don't have to worry about the Travis file, but you can comment it out of the other places if you want to get rid of it.

**Comment by DigiAngel** [comment]
Ah..I didn't think of looking at the docker-* files...go me!  Thank you!

**Comment by lhadjchikh** [comment]
No worries; I'll try to push an update that comments it out, so it doesn't trip anyone else up. :-) I also need to work on documentation for these files when I get a chance...

**Comment by lhadjchikh** [comment]
Removed cAdvisor from the Docker Compose files. https://github.com/dunbarcyber/cyphondock/commit/3c7dc40ffc21fb63aaf4ef6acf44d36707b6a498
