### ISSUE TITLE
Errors when following Cyphondock deployment script on a fresh Azure Ubuntu 16.04 VM

### ISSUE THREAD

**Issue by cruscio** [dunbarcyber/cyphondock#41]
Spun up a new VM on Azure and followed the [bash install](http://cyphondock.readthedocs.io/en/latest/configure-server.html#bash-install) server configuration steps by pasting commands one by one

Ubuntu Server 16.04 LTS amd64 20171011 Public Azure
Standard D4s v3 (4 vcpus, 16 GB memory) 

Full [screen.log](https://github.com/dunbarcyber/cyphondock/files/1435441/screen.log)  
Error message:

    $sudo docker exec -it cyphondock_cyphon_1 sh -c "python manage.py loaddata ./f 
    ixtures/starter-fixtures.json"
    An error occurred while closing Streams: could not connect to server: Connection refused
        Is the server running on host "postgres" (172.18.0.4) and accepting
        TCP/IP connections on port 5432?
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
        self.connect()
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
        self.connection = self.get_new_connection(conn_params)
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
        connection = Database.connect(**conn_params)
      File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
        conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "postgres" (172.18.0.4) and accepting
        TCP/IP connections on port 5432?
    
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "manage.py", line 26, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 68, in handle
        with transaction.atomic(using=self.using):
      File "/usr/local/lib/python3.6/site-packages/django/db/transaction.py", line 158, in __enter__
        if not connection.get_autocommit():
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 385, in get_autocommit
        self.ensure_connection()
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
        self.connect()
      File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
        self.connect()
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
        self.connection = self.get_new_connection(conn_params)
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
        connection = Database.connect(**conn_params)
      File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
        conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "postgres" (172.18.0.4) and accepting
        TCP/IP connections on port 5432?

**Comment by lhadjchikh** [comment]
This indicates that the Cyphon container can't talk to the PostgreSQL container that serves the database. Can you check the output of `sudo docker ps -a` to make sure the postgres container is running?

**Comment by cruscio** [comment]
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
    f0f5f7183766        nginx:1.13                                            "nginx -g 'daemon ..."   24 minutes ago      Up 24 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:5601->5601/tcp, 0.0.0.0:15672->15672/tcp   cyphondock_nginx_1
    03de805ac655        dunbar/cyphon:latest                                  "../entrypoints/ru..."   24 minutes ago      Up 24 minutes       8000/tcp                                                                                     cyphondock_celerybeat_1
    010d938a650d        dunbar/cyphon:latest                                  "../entrypoints/ru..."   24 minutes ago      Up 24 minutes       8000/tcp                                                                                     cyphondock_monitors_1
    1d64886cc828        dunbar/cyphon:latest                                  "../entrypoints/ru..."   24 minutes ago      Up 24 minutes       8000/tcp                                                                                     cyphondock_logchutes_1
    1b5181bf5ff3        dunbar/cyphon:latest                                  "../entrypoints/ru..."   24 minutes ago      Up 24 minutes       8000/tcp                                                                                     cyphondock_celeryworker_1
    82f8a5a0e7b7        dunbar/cyphon:latest                                  "../entrypoints/ru..."   24 minutes ago      Up 24 minutes       8000/tcp                                                                                     cyphondock_watchdogs_1
    d196aeb3e7f6        gliderlabs/logspout:latest                            "/bin/logspout sys..."   24 minutes ago      Up 24 minutes       80/tcp, 5000/udp                                                                             cyphondock_logspout_1
    b5f95dc026d6        dunbar/cyphon:latest                                  "/bin/sh -c $CYPHO..."   24 minutes ago      Up 24 minutes       8000/tcp                                                                                     cyphondock_cyphon_1
    837ee6e9f329        docker.elastic.co/logstash/logstash:5.6.1             "/usr/local/bin/do..."   24 minutes ago      Up 24 minutes       0.0.0.0:5044-5045->5044-5045/tcp, 9600/tcp                                                   cyphondock_logstash_1
    9b0e57434a2a        docker.elastic.co/kibana/kibana:5.6.1                 "/bin/sh -c /usr/l..."   24 minutes ago      Up 24 minutes       5601/tcp                                                                                     cyphondock_kibana_1
    5f4f10139701        mdillon/postgis:9.6                                   "docker-entrypoint..."   24 minutes ago      Up 24 minutes       5432/tcp                                                                                     cyphondock_postgres_1
    7149d285729a        docker.elastic.co/elasticsearch/elasticsearch:5.6.1   "/bin/bash bin/es-..."   24 minutes ago      Up 24 minutes       9200/tcp, 9300/tcp                                                                           cyphondock_elasticsearch_1
    4b6571998abe        dunbar/geoip                                          "crond -f -d 8"          24 minutes ago      Up 24 minutes                                                                                                    cyphondock_geoip_1
    038e8669fe95        rabbitmq:3.6-management                               "docker-entrypoint..."   24 minutes ago      Up 24 minutes       4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp                                          cyphondock_rabbit_1

**Comment by lhadjchikh** [comment]
Okay, thanks! That looks good. Can you try running the command again? It's possible you ran it before the postgres container had a chance to fully start. If it still doesn't work, can you check the logs?: `sudo docker-compose logs -f postgres`

**Comment by cruscio** [comment]
Still getting errors

    Last login: Wed Nov  1 19:53:59 2017 from 73.253.64.70
    opsadmin@cyphon:~$ sudo docker exec -it cyphondock_cyphon_1 sh -c "python manage.py loaddata ./fixtures/starter-fixtures.json"
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
    psycopg2.ProgrammingError: relation "reservoirs_reservoir" does not exist
    LINE 1: INSERT INTO "reservoirs_reservoir" ("name", "enabled") VALUE...
                        ^
    
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "manage.py", line 26, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
        self.loaddata(fixture_labels)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
        self.load_label(fixture_label)
      File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 175, in load_label
        obj.save(using=self.using)
      File "/usr/local/lib/python3.6/site-packages/django/core/serializers/base.py", line 205, in save
        models.Model.save_base(self.object, using=using, raw=True, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
        updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
      File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
        result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
      File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
        using=using, raw=raw)
      File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
        return query.get_compiler(using=using).execute_sql(return_id)
      File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
        cursor.execute(sql, params)
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.ProgrammingError: Problem installing fixture '/usr/src/app/cyphon/./fixtures/starter-fixtures.json': Could not load reservoirs.Reservoir(pk=None): relation "reservoirs_reservoir" does not exist
    LINE 1: INSERT INTO "reservoirs_reservoir" ("name", "enabled") VALUE...
                        ^
    
    opsadmin@cyphon:~$

Here's the log: [postgres.dockercompose.log](https://github.com/dunbarcyber/cyphondock/files/1435572/postgres.dockercompose.log)

**Comment by lhadjchikh** [comment]
Hmm, looks like Django migrations didn't run. Can you try `sudo docker exec -it cyphondock_cyphon_1 sh -c "python manage.py migrate"`?

**Comment by cruscio** [comment]
Success! Thanks

    opsadmin@cyphon:/opt/cyphon/cyphondock$ sudo docker exec -it cyphondock_cyphon_1 sh -c "python manage.py migrate"
    Operations to perform:
      Apply all migrations: actions, admin, alerts, appusers, articles, auth, bottles, categories, codebooks, collectionqueries, companies, containers, contenttypes, contexts, couriers, database, datachutes, datacondensers, datamungers, datasieves, destinations, dispatches, distilleries, django_mailbox, filters, followees, funnels, inspections, invoices, labels, locations, logchutes, logcondensers, logmungers, logsieves, mailchutes, mailcondensers, mailmungers, mailsieves, monitors, passports, pipes, plumbers, procedures, reservoirqueries, reservoirs, samples, searchterms, sessions, stamps, streams, tags, tastes, timeframes, visas, warehouses, watchdogs
    Running migrations:
      Applying destinations.0001_initial... OK
      Applying actions.0001_initial... OK
      
      
      [...]
      
      
      Applying timeframes.0001_initial... OK
      Applying watchdogs.0001_initial... OK
      Applying watchdogs.0002_auto_20170602_0914... OK
    opsadmin@cyphon:/opt/cyphon/cyphondock$ sudo docker exec -it cyphondock_cyphon_1 sh -c "python manage.py loaddata ./fixtures/starter-fixtures.json"
    Installed 425 object(s) from 1 fixture(s)
    opsadmin@cyphon:/opt/cyphon/cyphondock$
    
![image](https://user-images.githubusercontent.com/30699280/32296410-93a9fea8-bf22-11e7-86b3-d731cb15feee.png)

**Comment by lhadjchikh** [comment]
Great! I guess the postgres container hadn't fully started when the cyphon container tried to run migrations the first time around. So restarting the cyphon container might have worked, too. Anyway, glad it's working!
