### ISSUE TITLE
When using install script, it attempts to connect to a hardcoded postgres server

### ISSUE THREAD

**Issue by DelFireman** [dunbarcyber/cyphondock#55]
When using the automated install script, it fails as it appears to be attempting to connect to a postgres database.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
**psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "postgres" (172.18.0.4) and accepting
	TCP/IP connections on port 5432?**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 68, in handle
    with transaction.atomic(using=self.using):
  File "/usr/local/lib/python3.6/site-packages/django/db/transaction.py", line 158, in __enter__
    if not connection.get_autocommit():
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 385, in get_autocommit
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
**django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "postgres" (172.18.0.4) and accepting
	TCP/IP connections on port 5432?**

**Comment by lhadjchikh** [comment]
Hi @DelFireman. Yes, it's attempting to connect to the PostgreSQL database that Django uses. It's likely the postgres container had not started quickly enough, so the database was unavailable when Django tried to load data from the starter fixtures. I would try to run the last two commands manually (`loaddata` and `createsuperuser`) after the postgres container has had a chance to fully start. We should probably modify the script to sleep for a bit before it tries to load those fixtures.

**Comment by DelFireman** [comment]
Ok.  Thanks @lhadjchikh .  Makes sense as I had copied the startup script to file to run.

**Comment by lhadjchikh** [comment]
Fixed in https://github.com/dunbarcyber/cyphondock/commit/a2c3c4d197ae3fdb25bf5ab3d3f1adc61ed18ab4.
