### ISSUE TITLE
Problem with elasticsearch container in cyphondock

### ISSUE THREAD

**Issue by Phoenie1** [dunbarcyber/cyphondock#63]
Hello.  I just installed cyphondock, and the elasticsearch container keeps restarting.  Anyone else have experience with this problem?

Running Ubuntu 16.04 with Docker CE

**Comment by lhadjchikh** [comment]
It's likely a problem with file permissions. See if this helps: https://github.com/dunbarcyber/cyphon/issues/300

**Comment by Phoenie1** [comment]
No, not the problem.  I keep getting this in the log:

OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000085330000, 2060255232, 0) failed; error='Cannot allocate memory' (errno=12)


I've already reduced the Java heap size from 2G to 512M, and it's done no good - it;s like regardless what I do, Java is determined to allocate 2G.  Still don't know why this would be a problem when I have tons of memory, anyway:

free -h
              total        used        free      shared  buff/cache   available
Mem:            14G        1.5G         11G         22M        1.6G         13G
Swap:          4.0G          0B        4.0G


Any ideas would be helpful.  Cyphon looks like exactly what I need, but I 've been hacking away at this problem for 2 days and can't spend any more time on it.

**Comment by darvid** [comment]
That's really strange...I wouldn't suggest reducing the heap size to anything below 2 GB, though, and it looks like you have plenty of memory to work with. How did you go about trying to reduce the heap size, though? Did you edit the ``config/elasticsearch/jvm.options`` file?

Could you provide the version of Docker you're running? If other containers are running, could you paste the output of ``docker stats``?

**Comment by darvid** [comment]
Looks like Elasticsearch is running currently, how frequently does it restart/how long does it stay up? 

Have you tried removing the container and recreating it? You can do that with:

```
docker-compose stop elasticsearch
docker-compose rm elasticsearch
docker-compose up -d elasticsearch
```

**Comment by Phoenie1** [comment]
That helped some.  Before it was restarting/staying up every 20 seconds or so.  Now it's up to a minute and isn't complaining about memory, but I do get this:

[2018-02-08T21:22:42,909][INFO ][o.e.n.Node               ] [] initializing ...
[2018-02-08T21:22:42,977][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.5.jar:5.6.5]
Caused by: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.node.Node.<init>(Node.java:268) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.5.jar:5.6.5]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.5.jar:5.6.5]
        ... 6 more

**Comment by lhadjchikh** [comment]
Ah, okay, that's related to https://github.com/dunbarcyber/cyphondock/issues/54.

**Comment by lhadjchikh** [comment]
Closing this due to inactivity, but feel free to reopen if you're still having issues.
